#!/usr/bin/env python3
"""
AWS Data Profiling Pipeline — HTML Reporter
Version: 1.1
"""

import argparse
import json
import os
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AWDPP Data Profiling Report</title>
    <style>
        :root {{
            --bg: #0f172a;
            --surface: #1e293b;
            --surface-hover: #334155;
            --text: #f1f5f9;
            --text-muted: #94a3b8;
            --accent: #38bdf8;
            --accent-dim: #0ea5e9;
            --success: #4ade80;
            --warning: #fbbf24;
            --danger: #f87171;
            --border: #334155;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
        }}
        .container {{ max-width: 1400px; margin: 0 auto; }}
        header {{
            text-align: center;
            padding: 2rem 0;
            border-bottom: 1px solid var(--border);
            margin-bottom: 2rem;
        }}
        h1 {{ font-size: 2rem; font-weight: 700; letter-spacing: -0.02em; }}
        .subtitle {{ color: var(--text-muted); margin-top: 0.5rem; }}
        .meta-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }}
        .meta-card {{
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 1.25rem;
        }}
        .meta-label {{ font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em; color: var(--text-muted); margin-bottom: 0.25rem; }}
        .meta-value {{ font-size: 1.125rem; font-weight: 600; font-family: monospace; }}
        .section {{ margin-bottom: 2rem; }}
        .section-title {{
            font-size: 1.25rem;
            font-weight: 600;
            margin-bottom: 1rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            overflow: hidden;
            font-size: 0.875rem;
        }}
        th, td {{ padding: 0.75rem 1rem; text-align: left; }}
        th {{
            background: var(--surface-hover);
            font-weight: 600;
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            position: sticky;
            top: 0;
        }}
        tr {{ border-bottom: 1px solid var(--border); }}
        tr:last-child {{ border-bottom: none; }}
        tr:hover {{ background: rgba(255,255,255,0.03); }}
        td {{ font-family: monospace; font-size: 0.8125rem; }}
        .badge {{
            display: inline-block;
            padding: 0.125rem 0.5rem;
            border-radius: 999px;
            font-size: 0.6875rem;
            font-weight: 600;
            text-transform: uppercase;
        }}
        .badge-varchar {{ background: rgba(56, 189, 248, 0.15); color: var(--accent); }}
        .badge-int {{ background: rgba(74, 222, 128, 0.15); color: var(--success); }}
        .badge-double {{ background: rgba(251, 191, 36, 0.15); color: var(--warning); }}
        .badge-date {{ background: rgba(248, 113, 113, 0.15); color: var(--danger); }}
        .null-bar {{
            height: 4px;
            background: var(--surface-hover);
            border-radius: 2px;
            overflow: hidden;
            margin-top: 0.25rem;
        }}
        .null-bar-fill {{
            height: 100%;
            background: var(--warning);
            border-radius: 2px;
        }}
        .rejected-banner {{
            background: rgba(248, 113, 113, 0.1);
            border: 1px solid var(--danger);
            border-radius: 12px;
            padding: 1rem;
            margin-bottom: 2rem;
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }}
        .footer {{
            text-align: center;
            color: var(--text-muted);
            font-size: 0.75rem;
            margin-top: 3rem;
            padding-top: 2rem;
            border-top: 1px solid var(--border);
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Data Profiling Report</h1>
            <p class="subtitle">Generated by AWS Data Profiling Pipeline v1.1</p>
        </header>

        <div class="meta-grid">
            <div class="meta-card">
                <div class="meta-label">Report Generated</div>
                <div class="meta-value">{generated_at}</div>
            </div>
            <div class="meta-card">
                <div class="meta-label">Source File</div>
                <div class="meta-value">{source_file}</div>
            </div>
            <div class="meta-card">
                <div class="meta-label">SHA256 Hash</div>
                <div class="meta-value" style="font-size:0.75rem;">{sha256_hash}</div>
            </div>
            <div class="meta-card">
                <div class="meta-label">Total Columns</div>
                <div class="meta-value">{total_columns}</div>
            </div>
        </div>

        {rejected_banner}

        <div class="section">
            <h2 class="section-title">Column Summary</h2>
            <table>
                <thead>
                    <tr>
                        <th>Column</th>
                        <th>Type</th>
                        <th>Min</th>
                        <th>Max</th>
                        <th>Avg</th>
                        <th>Null %</th>
                        <th>Unique</th>
                    </tr>
                </thead>
                <tbody>
                    {table_rows}
                </tbody>
            </table>
        </div>

        <div class="footer">
            AWS Data Profiling Pipeline &bull; DuckDB-powered &bull; {generated_at}
        </div>
    </div>
</body>
</html>
"""


def generate_report(input_dir: str, output_path: str):
    input_path = Path(input_dir)

    # Load summary JSON
    summary_json = input_path / "summary.json"
    if not summary_json.exists():
        raise FileNotFoundError(f"Summary JSON not found: {summary_json}")

    with open(summary_json, "r") as f:
        records = json.load(f)

    # Load SHA256 if available
    sha256_file = input_path / "sha256.txt"
    sha256_hash = sha256_file.read_text().strip() if sha256_file.exists() else "N/A"

    # Check for rejected rows
    rejected_csv = input_path / "rejected.csv"
    rejected_banner = ""
    if rejected_csv.exists():
        with open(rejected_csv, "r") as f:
            rejected_count = sum(1 for _ in f) - 1  # minus header
        rejected_banner = f"""
        <div class="rejected-banner">
            <span>⚠️</span>
            <div>
                <strong>Rejected Rows Detected:</strong> {rejected_count} malformed row(s) found.
                See <code>rejected.csv</code> for details.
            </div>
        </div>
        """

    # Build table rows
    rows = []
    for rec in records:
        col_name = rec.get("column_name") or rec.get("column") or "Unknown"
        col_type = rec.get("column_type", "VARCHAR")
        min_val = str(rec.get("min", ""))[:50]
        max_val = str(rec.get("max", ""))[:50]
        avg_val = str(rec.get("avg", ""))[:50]
        null_pct = rec.get("null_percentage", 0) or 0
        unique_count = rec.get("unique", "N/A")

        type_class = "badge-varchar"
        if "INT" in str(col_type).upper():
            type_class = "badge-int"
        elif "DOUBLE" in str(col_type).upper() or "FLOAT" in str(col_type).upper() or "DECIMAL" in str(col_type).upper():
            type_class = "badge-double"
        elif "DATE" in str(col_type).upper() or "TIME" in str(col_type).upper():
            type_class = "badge-date"

        null_width = min(float(null_pct) * 5, 100)  # scale for visual

        rows.append(f"""
            <tr>
                <td><strong>{col_name}</strong></td>
                <td><span class="badge {type_class}">{col_type}</span></td>
                <td>{min_val}</td>
                <td>{max_val}</td>
                <td>{avg_val}</td>
                <td>
                    {null_pct:.2f}%
                    <div class="null-bar"><div class="null-bar-fill" style="width:{null_width}%"></div></div>
                </td>
                <td>{unique_count}</td>
            </tr>
        """)

    from datetime import datetime
    html = HTML_TEMPLATE.format(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        source_file=input_path.name,
        sha256_hash=sha256_hash,
        total_columns=len(records),
        rejected_banner=rejected_banner,
        table_rows="\n".join(rows),
    )

    with open(output_path, "w") as f:
        f.write(html)

    print(f"HTML report generated: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="AWDPP HTML Reporter")
    parser.add_argument("--input-dir", required=True, help="Directory containing summary.json")
    parser.add_argument("--output", required=True, help="Output HTML file path")
    args = parser.parse_args()

    generate_report(args.input_dir, args.output)


if __name__ == "__main__":
    main()